    # To limit exposure to denial-of-service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
    # See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      resourcedetection:
        detectors: ["env", "system"]
        override: false


    exporters:
      debug:
        verbosity: detailed
      #otlphttp/logs:
      #  endpoint: "http://loki:3100/otlp"
      #  tls:
      #    insecure: true
      otlphttp/grafana_cloud:
        endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}"
        auth:
          authenticator: basicauth/grafana_cloud

    extensions:
      basicauth/grafana_cloud:
        client_auth:
          username: "${env:GRAFANA_CLOUD_INSTANCE_ID}"
          password: "${env:GRAFANA_CLOUD_API_KEY}"

    service:
      extensions:
        [ basicauth/grafana_cloud ]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ debug ]
        logs:
          receivers: [ otlp ]
          processors: [  resourcedetection, batch ]
          exporters: [ debug, otlphttp/grafana_cloud ]


