    # To limit exposure to denial-of-service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
    # See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      transform:
        error_mode: ignore
        log_statements:
          - context: log
            conditions:
              - body != nil and Substring(body, 0, 2) == "{\""
            statements:
              - merge_maps(cache, ParseJSON(body), "upsert")
              - set(attributes["policy.id"], cache["policy"]["uid"])
              - set(attributes["policy.evaluation.status"], cache["status"])
              - set(attributes["policy.source"], cache["metadata"]["product"]["name"])
              - set(attributes["policy.enforcement.action"], cache["action"])
              - set(attributes["category.id"], cache["category_uid"])
              - set(attributes["class.id"], cache["class_uid"])
              - set(observed_time, Now()) where observed_time_unix_nano == 0
              - set(time, observed_time) where time_unix_nano == 0
              - flatten(cache, "")
              - merge_maps(attributes, cache, "upsert")

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ debug ]
        logs:
          # TODO: Grafana Cloud Free Tier
          receivers: [ otlp ]
          processors: [ batch, transform ]
          exporters: [ debug ]


