# Enhanced collector configuration for debugging
# To limit exposure to denial-of-service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  attributes/pii-redact:
    actions:
      - key: github.event.pusher.email
        action: delete
  attributes/env:
    actions:
      - key: deployment.environment
        value: prod
        action: insert
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["compliance.standards"], ["800-53"])
          - set(attributes["compliance.status"], "Fail") where attributes["policy.enforcement.status"] == "fail"
          - set(attributes["compliance.requirements"], ["SA-11(4)"]) where attributes["policy.id"] == "github_branch_protection"

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlphttp/grafana_cloud:
    endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}"
    auth:
      authenticator: basicauth/grafana_cloud
    # Add retry configuration
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    # Add timeout configuration
    timeout: 10s

extensions:
  basicauth/grafana_cloud:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension
    client_auth:
      username: "${env:GRAFANA_CLOUD_INSTANCE_ID}"
      password: "${env:GRAFANA_CLOUD_API_KEY}"

service:
  telemetry:
    logs:
      level: DEBUG
    metrics:
      level: detailed
  extensions:
    [ basicauth/grafana_cloud ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    logs:
      receivers: [ otlp ]
      processors: [ attributes/env, transform, batch ]
      exporters: [ debug, otlphttp/grafana_cloud ]
