name: Transform Governance Rules to Policy as Code

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - checks/**

permissions: {}

env:
  AP: "assessment-plan-${{ github.run_id }}.json"

jobs:
  generate-policy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.24'
          cache: false
          check-latest: true

      - name: Setup c2pcli
        uses: jpower432/c2p-actions/actions/setup-c2pcli@0bc42f492f3a6854fe0afc99c50100db8f5e17c6 # main

      - name: Setup plugin dir
        run: mkdir -p c2p-plugins policies policy-results

      - name: Install C2P plugins
        uses: ./.github/actions/install-plugin
        with:
          install-dir: './c2p-plugins'

      - name: Create Assessment Plan
        run: |
          go run ./cmd/transformer-kit plan -t "GitHub Repository" -r SSDF > "${AP}"

      - name: Generate policy bundle
        run: c2pcli oscal2policy -c configs/c2p-config.yaml -a "${AP}"

      - uses: actions/upload-artifact@v4
        with:
          name: assessment-plan
          path: ${{ env.AP }}
          retention-days: 5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.62.0/conftest_0.62.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.62.0_Linux_x86_64.tar.gz

      - name: Push bundle
        env:
          ORG: ${{ github.event.repository.owner.login }}
        run: ./conftest push "ghcr.io/$ORG/policy-bundle:dev" -p ./policies/policy